# -*- coding: utf-8 -*-
# English -> Chinese translation table for the three British Museum pages.
T = {
# ---------- <head> / meta ----------
"Explore more than 60 galleries at the British Museum.": "探索大英博物馆的60多个展厅。",
"Galleries": "展厅",
"Discover over 60 free galleries at the British Museum, featuring ancient artefacts and diverse cultural exhibits across multiple floors.": "探索大英博物馆60多个免费开放的展厅，多个楼层展出古代文物与丰富多元的文化展品。",
"Galleries | British Museum": "展厅 | 大英博物馆",
"Enlightenment | British Museum": "启蒙运动 | 大英博物馆",
"Africa | British Museum": "非洲 | 大英博物馆",
"The Enlightenment was an age of reason and learning that flourished across Europe and America from about 1680 to 1820.": "启蒙运动是一个崇尚理性与学问的时代，约1680年至1820年间在欧洲和美洲蓬勃兴起。",

# ---------- header / navigation ----------
"Skip to main content": "跳转到主要内容",
"Please enable JavaScript in your web browser to get the best experience.": "请在浏览器中启用JavaScript，以获得最佳浏览体验。",
"Home": "首页",
"British Museum": "大英博物馆",
"Menu": "菜单",
"Main navigation": "主导航",
"Visit": "参观",
"Back": "返回",
"to previous menu": "上一级菜单",
"Plan your visit": "规划参观",
"Family visits": "家庭参观",
"Group visits": "团体参观",
"Audio app": "语音导览应用",
"Out-of-hours tours": "闭馆时段专场导览",
"Tours and talks": "导览与讲座",
"Object trails": "文物主题路线",
"Accessibility": "无障碍服务",
"Food and drink": "餐饮",
"Late opening on Fridays": "周五夜场",
"Museum map": "博物馆地图",
"Exhibitions and events": "展览与活动",
"Collection": "馆藏",
"Collection online": "在线馆藏",
"Blog": "博客",
"The British Museum podcast": "大英博物馆播客",
"Learn": "学习",
"Learning with the Museum": "与博物馆一起学习",
"Schools": "学校",
"Communities": "社区",
"Adult learning": "成人学习",
"Young people": "青少年",
"Membership": "会员",
"Become a Member": "成为会员",
"Members' events": "会员活动",
"Young Friends": "青年之友",
"Existing Members": "现有会员",
"Visiting as a Member": "会员参观",
"Support us": "支持我们",
"How to support us": "如何支持我们",
"Donate": "捐赠",
"Corporate support": "企业支持",
"Become a Patron": "成为赞助人",
"Supporter case studies": "支持者案例",
"Become a Volunteer": "成为志愿者",
"Existing Patrons": "现有赞助人",
"Leave a legacy": "遗赠捐助",
"American Friends of the British Museum": "大英博物馆美国之友",
"Secondary navigation": "次级导航",
"Shop": "商店",
"(Opens in new window)": "（在新窗口中打开）",
"Search": "搜索",
"Hide menu": "隐藏菜单",

# ---------- hero / share ----------
"Visitors standing in the Parthenon gallery": "站在帕特农展厅中的参观者",
"Show image caption": "显示图片说明",
"Close image caption": "关闭图片说明",
"Visitors standing in the Parthenon gallery (Room 18)": "站在帕特农展厅（第18展厅）中的参观者",
"You are in the Collection section": "您当前位于“馆藏”栏目",
"You are in the Galleries section": "您当前位于“展厅”栏目",
"Share the page": "分享本页",
"Share on Facebook": "分享到Facebook",
"Share on X (formerly Twitter)": "分享到X（原Twitter）",
"Share using email": "通过电子邮件分享",
"Share on WhatsApp": "分享到WhatsApp",
"On this page": "本页内容",
"Lower floor": "地下层",
"Ground floor": "底层",
"Upper floors": "楼上各层",
"Virtual galleries": "虚拟展厅",

# ---------- galleries intro ----------
"Visiting the galleries": "参观展厅",
"Opening times": "开放时间",
"Daily: 10.00–17.00": "每日：10:00–17:00",
"See full": "查看完整",
"opening hours": "开放时间",
"View the Museum map": "查看博物馆地图",
"Explore more than 60 galleries at the British Museum from home.": "足不出户，探索大英博物馆的60多个展厅。",
"Our gallery pages feature a range of exciting resources, including virtual tours with Google Street View, object highlights, timelines, family activities and facts.": "我们的展厅页面提供丰富精彩的资源，包括谷歌街景虚拟导览、重点展品、时间线、家庭活动以及趣味知识。",
"Below you'll find a list of galleries on the lower floor, ground floor and upper floors, together with two galleries created especially for our online audience,": "下方列出了地下层、底层和楼上各层的展厅，以及两个专为线上观众打造的展厅：",
"Oceania": "大洋洲",
"and": "和",
"Prints and Drawings": "版画与素描",
"Please note that galleries in the Museum may be closed for maintenance, refurbishment or private events. All planned closures will be listed on the": "请注意，博物馆内的展厅可能因维护、翻新或私人活动而关闭。所有计划内的闭馆信息都会公布在",
"Visit page": "参观页面",
". Occasionally we may need to close galleries at short notice for safety reasons. We regret that in these cases we're not always able to alert the public in advance.": "上。有时出于安全原因，我们可能需要临时关闭展厅。很遗憾，在这种情况下我们未必能够提前通知公众。",

# ---------- museum highlights ----------
"Museum highlights": "博物馆精选",
"Statue of Ramesses II in the Egyptian sculpture gallery": "埃及雕塑展厅中的拉美西斯二世雕像",
"Egyptian sculpture gallery": "埃及雕塑展厅",
"Travel back through 3,000 years of history via our timeline and gallery. Discover the Rosetta Stone, Statue of Ramesses II and more.": "借助我们的时间线和展厅，穿越3000年历史。探索罗塞塔石碑、拉美西斯二世雕像等众多珍宝。",
"Rectangular in form with side flanges (largely missing). Background surface decorated with stylised quatrefoil (river leaf) patterns and stippling. Rosettes in each corner": "长方形饰板，两侧带有凸缘（大部分已缺失）。背景饰有程式化的四叶纹（河叶纹）和点刻纹，四角各有一朵玫瑰花饰",
"Africa": "非洲",
"The Sainsbury Africa Galleries reveal the extraordinary cultural, artistic and historical diversity and complexity of the continent.": "塞恩斯伯里非洲展厅展现了非洲大陆在文化、艺术和历史上非凡的多样性与复杂性。",
"Visitor looking at the Sutton Hoo helmet in Room 41": "在第41展厅观看萨顿胡头盔的参观者",
"Sutton Hoo and Europe": "萨顿胡与欧洲",
"Spanning over 700 years, this Room traces the story of Europe from 300 AD.": "本展厅跨越700多年，追溯自公元300年起的欧洲历史。",
"Visit Room 41": "参观第41展厅",
"Visitor looking at a marble bust in Room 70": "在第70展厅观看大理石半身像的参观者",
"Roman Empire": "罗马帝国",
"The objects in Room 70 illustrate the rise of Rome from a small town to an imperial capital.": "第70展厅的展品展示了罗马从一座小城崛起为帝国首都的历程。",
"Visit Room 70": "参观第70展厅",

# ---------- gallery list ----------
"Wooden figure, focus on face with closed eyes and mouth.": "木雕人像，面部特写，双眼与嘴巴紧闭。",
"Room 25 (": "第25展厅 (",
"The Sainsbury Galleries": "塞恩斯伯里展厅",
"Visit Room 25": "参观第25展厅",
"image of marble statue of a discus thrower": "掷铁饼者大理石雕像图片",
"Enlightenment": "启蒙运动",
"Room 1": "第1展厅",
"Visit Room 1": "参观第1展厅",
"Gold pendant in the shape of a heart with enamelled rose and pomegranate, held on a gold chain by a clasp in the shape of a hand.": "心形金吊坠，饰有珐琅玫瑰与石榴图案，由一只手形扣环挂在金链上。",
"Collecting the world": "收藏世界",
"Room 2": "第2展厅",
"Visit Room 2": "参观第2展厅",
"Holy Thorn reliquary gold and jewels": "黄金珠宝圣荆棘圣物匣",
"The Waddesdon Bequest": "沃德斯登遗赠",
"Room 2a": "第2a展厅",
"(funded by The Rothschild Foundation)": "（由罗斯柴尔德基金会资助）",
"Visit Room 2a": "参观第2a展厅",
"Head and upper body of pink/grey granite monumental statue of Ramesses II.": "粉灰色花岗岩拉美西斯二世巨像的头部和上半身。",
"Egyptian sculpture": "埃及雕塑",
"Room 4": "第4展厅",
"Visit Room 4": "参观第4展厅",
"Statue of a winged lion from the North-West Palace of Ashurnasirpal II": "出自亚述纳西拔二世西北宫的有翼狮像",
"Assyrian sculpture and Balawat Gates": "亚述雕塑与巴拉瓦特城门",
"Room 6a": "第6a展厅",
"Visit Room 6": "参观第6展厅",
"Stone panel from the North-West Palace of Ashurnasirpal II, Assyria, 883-859 BC.": "亚述纳西拔二世西北宫石板浮雕，亚述，公元前883–前859年。",
"Assyria: Nimrud": "亚述：尼姆鲁德",
"Rooms 7–8": "第7–8展厅",
"Visit Rooms 7–8": "参观第7–8展厅",
"Frieze with drawings on it": "带有图像的浮雕饰带",
"Assyria: Nineveh": "亚述：尼尼微",
"Room 9": "第9展厅",
"Visit Room 9": "参观第9展厅",
"Large relief with men pulling a horse": "描绘人们牵马的大型浮雕",
"Assyria: Lion hunts, Siege of Lachish and Khorsabad": "亚述：猎狮、拉吉之围与豪尔萨巴德",
"Room 10": "第10展厅",
"Visit Room 10": "参观第10展厅",
"Gold goblet": "金高脚杯",
"Greece: Minoans and Mycenaeans": "希腊：米诺斯人与迈锡尼人",
"Room 12 (": "第12展厅 (",
"The Arthur I Fleischman Gallery)": "阿瑟·I·弗莱施曼展厅)",
"Visit Room 12": "参观第12展厅",
"Greek wine jar depicting Achilles defeating Penthesilea, the Amazon Queen.": "描绘阿喀琉斯击败亚马逊女王彭忒西勒亚的希腊酒罐。",
"Greece 1050–520 BC": "希腊，公元前1050–前520年",
"Room 13": "第13展厅",
"Visit Room 13": "参观第13展厅",
"Greek vase depicting black-figured neck-amphora, signed by the potter Andokides.": "希腊黑绘颈柄双耳瓶，带有陶工安多基德斯的签名。",
"Greek vases": "希腊陶瓶",
"Room 14": "第14展厅",
"Visit Room 14": "参观第14展厅",
"Large Greek relief panel featuring a female-headed bird": "饰有女首鸟身形象的大型希腊浮雕板",
"Athens and Lycia": "雅典与吕基亚",
"Room 15": "第15展厅",
"Visit Room 15": "参观第15展厅",
"The Bassai Sculptures, the Phigaleian Frieze, Classical Greek": "巴赛雕塑，菲加利亚饰带，古典希腊时期",
"Greece: Bassai sculptures": "希腊：巴赛雕塑",
"Room 16": "第16展厅",
"Visit Room 16": "参观第16展厅",
"Visitors in Room 17 by the Nereid Monument": "第17展厅中涅瑞伊得斯纪念碑旁的参观者",
"Nereid Monument": "涅瑞伊得斯纪念碑",
"Room 17": "第17展厅",
"Visit Room 17": "参观第17展厅",
"Marble sculpture of horses head from parthenon": "帕特农神庙的大理石马头雕塑",
"Greece: Parthenon": "希腊：帕特农神庙",
"Room 18": "第18展厅",
"Visit Room 18": "参观第18展厅",
"Marble block from the west frieze of the Temple of Athena Nike": "雅典娜胜利女神庙西侧饰带的大理石块",
"Greece: Athens": "希腊：雅典",
"Room 19": "第19展厅",
"Visit Room 19": "参观第19展厅",
"Marble head of a youthful god: the 'Aberdeen Head', Classical Greek, 325-280 BC": "年轻神祇的大理石头像：“阿伯丁头像”，古典希腊时期，公元前325–前280年",
"Greeks and Lycians 400–325 BC": "希腊人与吕基亚人，公元前400–前325年",
"Room 20": "第20展厅",
"Visit Room 20": "参观第20展厅",
"Horse head made from marble": "大理石马头",
"Mausoleum of Halikarnassos": "哈利卡纳苏斯的摩索拉斯王陵墓",
"Room 21": "第21展厅",
"Visit Room 21": "参观第21展厅",
"Marble statue of Demeter seated on a throne, Greek, carved around 350 BC.": "端坐于宝座上的得墨忒耳大理石像，希腊，约公元前350年雕刻。",
"The world of Alexander": "亚历山大的世界",
"Room 22": "第22展厅",
"Visit Room 22": "参观第22展厅",
"Marble relief featuring a boy and horse.": "刻有少年与马的大理石浮雕。",
"Greek and Roman sculpture": "希腊与罗马雕塑",
"Room 23": "第23展厅",
"Visit Room 23": "参观第23展厅",
"Large human figure made of stone.": "大型石质人像。",
"Living and Dying": "生与死",
"Room 24 (": "第24展厅 (",
"The Wellcome Trust Gallery": "惠康基金会展厅",
"Visit Room 24": "参观第24展厅",
"Snow sled brown in colour.": "棕色雪橇。",
"North America": "北美洲",
"Room 26": "第26展厅",
"Visit Room 26": "参观第26展厅",
"Image of a turquoise mosaic covered serpent with two heads": "绿松石马赛克双头蛇图片",
"Mexico": "墨西哥",
"Room 27": "第27展厅",
"Visit Room 27": "参观第27展厅",
"Colossal marble statue of a lion in the Great Court.": "大中庭内的巨型大理石狮像。",
"Great Court": "大中庭",
"The Great Court": "大中庭",
"Frieze with figure of a man and a lion": "刻有人物与狮子形象的饰带",
"East stairs": "东侧楼梯",
"Visit the East stairs": "参观东侧楼梯",
"4 humans 1 horse 1 camel all figures are shades of white, brown and green.": "四个人物、一匹马和一头骆驼，均呈白、棕、绿等色调。",
"China and South Asia": "中国与南亚",
"Room 33 (": "第33展厅 (",
"The Sir Joseph Hotung Gallery": "何鸿卿爵士展厅",
"Visit Room 33": "参观第33展厅",
"Dome-slab carved in limestone with the Great Departure, Prince Siddhartha's horse Kanthaka with empty saddle leaving the palace via an elaborate torana (gate)": "石灰岩穹顶石板，刻有“逾城出家”场景：悉达多太子的坐骑犍陟背着空鞍，穿过华美的陀兰那（门楼）离开王宫",
"India: Amaravati": "印度：阿马拉瓦蒂",
"Room 33a (": "第33a展厅 (",
"The Asahi Shimbun Gallery": "朝日新闻展厅",
"Visit Room 33a": "参观第33a展厅",
"A jade brush pot decorated with nature motifs": "饰有自然纹样的玉笔筒",
"Chinese jade": "中国玉器",
"Room 33b (": "第33b展厅 (",
"The Selwyn and Ellie Alleyne Gallery": "塞尔温与埃莉·阿莱恩展厅",
"Visit Room 33b": "参观第33b展厅",
"Cassiobury Park turret clock": "卡西奥伯里公园塔钟",
"Clocks and watches": "钟表",
"Rooms 38–39 (": "第38–39展厅 (",
"The Sir Harry and Lady Djanogly Gallery": "哈里·贾诺格利爵士与夫人展厅",
"Visit Rooms 38–39": "参观第38–39展厅",
"Seven white chess pieces": "七枚白色棋子",
"Medieval Europe, 1050–1500": "中世纪欧洲，1050–1500年",
"Room 40 (": "第40展厅 (",
"The Sir Paul and Lady Ruddock Gallery": "保罗·拉多克爵士与夫人展厅",
"Visit Room 40": "参观第40展厅",
"Sutton hoo helmet": "萨顿胡头盔",
"Sutton Hoo and Europe, AD 300–1100": "萨顿胡与欧洲，公元300–1100年",
"Room 41 (": "第41展厅 (",
"Jade terrapin on blue background": "蓝色背景上的玉龟",
"The Islamic world": "伊斯兰世界",
"Rooms 42–43 (": "第42–43展厅 (",
"The Albukhary Foundation Gallery": "阿尔布哈里基金会展厅",
"Visit Rooms 42–43": "参观第42–43展厅",
"Large blue and yellow decorated vase.": "蓝黄两色装饰的大花瓶。",
"Europe 1400–1800": "欧洲，1400–1800年",
"Room 46": "第46展厅",
"Visit Room 46": "参观第46展厅",
"Vase made of pale blue jasper ware with applied white reliefs": "饰有白色贴花浮雕的淡蓝色碧玉细炻器花瓶",
"Europe 1800–1900": "欧洲，1800–1900年",
"Room 47": "第47展厅",
"Visit Room 47": "参观第47展厅",
"Yellow and black squared mantelpiece clock": "黄黑方格壁炉座钟",
"Europe 1900 to the present": "欧洲，1900年至今",
"Room 48": "第48展厅",
"Visit Room 48": "参观第48展厅",
"The Great dish from the Mildenhall Treasure, a large concave silver platter with beaded rim (135 beads in total) on a circular vertical foot-ring positioned exactly one-third in from the rim.": "米尔登霍尔宝藏中的“大银盘”：一只大型凹面银盘，盘沿饰有联珠纹（共135颗），下承圆形直立圈足，圈足恰好位于距盘沿三分之一处。",
"Roman Britain": "罗马时期的不列颠",
"Room 49 (": "第49展厅 (",
"The Weston Gallery": "韦斯顿展厅",
"Visit Room 49": "参观第49展厅",
"a Golden round torc with circle gold balls at each end": "两端饰有金球的圆形金项圈",
"Britain and Europe 800 BC–AD 43": "不列颠与欧洲，公元前800年–公元43年",
"Room 50": "第50展厅",
"Visit Room 50": "参观第50展厅",
"A gold cape to be placed through head and sit on shoulders.": "一件从头部套入、披在肩上的黄金披肩。",
"Europe and Middle East 10,000–800 BC": "欧洲与中东，公元前10000–前800年",
"Room 51 (": "第51展厅 (",
"The Sheikh Zayed Bin Sultan Al Nahyan Gallery": "谢赫·扎耶德·本·苏尔坦·阿勒纳哈扬展厅",
"Visit Room 51": "参观第51展厅",
"Gold armlet with two dragon looking figures attached.": "饰有两个龙形兽首的金臂环。",
"Ancient Iran": "古代伊朗",
"Room 52 (": "第52展厅 (",
"The Rahim Irvani Gallery": "拉希姆·伊尔瓦尼展厅",
"Visit Room 52": "参观第52展厅",
"Ancient Arabian calcite incense burner showing a camel rider": "刻有骆驼骑手形象的古阿拉伯方解石香炉",
"Ancient South Arabia": "古代南阿拉伯",
"Room 53": "第53展厅",
"Visit Room 53": "参观第53展厅",
"Ivory figure of a griffin-headed demon, Anatolia": "格里芬首恶魔象牙雕像，安纳托利亚",
"Anatolia and Urartu, 7000–300 BC": "安纳托利亚与乌拉尔图，公元前7000–前300年",
"Room 54": "第54展厅",
"Visit Room 54": "参观第54展厅",
"Map of the World, Mesopotamia, 700-500 BC.": "世界地图，美索不达米亚，公元前700–前500年。",
"Mesopotamia, 1500–539 BC": "美索不达米亚，公元前1500–前539年",
"Room 55": "第55展厅",
"Visit Room 55": "参观第55展厅",
"Mesopotamian sculpture of queen of the night woman with wings": "美索不达米亚“夜之女王”浮雕：一位生有双翼的女性",
"Mesopotamia, 6000–1500 BC": "美索不达米亚，公元前6000–前1500年",
"Room 56": "第56展厅",
"Visit Room 56": "参观第56展厅",
"Small white statue of male figure sitting down": "白色小型男性坐像",
"Ancient Levant": "古代黎凡特",
"Rooms 57–59": "第57–59展厅",
"Visit Rooms 57–59": "参观第57–59展厅",
"scene of man hunting egyptian painting": "描绘男子狩猎场景的埃及壁画",
"Egyptian life and death: the tomb-chapel of Nebamun": "埃及的生与死：内巴蒙墓室礼拜堂",
"Room 61 (": "第61展厅 (",
"The Michael Cohen Gallery": "迈克尔·科恩展厅",
"Visit Room 61": "参观第61展厅",
"A gold decorated coffin in the shape of a human.": "饰金人形棺。",
"Egyptian death and afterlife: mummies": "埃及的死亡与来世：木乃伊",
"Rooms 62–63 (": "第62–63展厅 (",
"The Roxie Walker Galleries": "罗克西·沃克展厅",
"Visit Rooms 62–63": "参观第62–63展厅",
"Granite statue of Ankhwa, one hand on leg the other holding a tool.": "安赫瓦花岗岩雕像，一手放在腿上，另一手握着工具。",
"Early Egypt": "早期埃及",
"Room 64": "第64展厅",
"Visit Room 64": "参观第64展厅",
"Lying down sphinx, human head light brown.": "卧姿斯芬克斯，人首呈浅棕色。",
"Sudan, Egypt and Nubia": "苏丹、埃及与努比亚",
"Room 65": "第65展厅",
"Visit Room 65": "参观第65展厅",
"Oil painting on cotton cloth, depicting the a battle scene.": "绘于棉布上的油画，描绘了一场战斗场景。",
"Ethiopia and Coptic Egypt": "埃塞俄比亚与科普特埃及",
"Room 66": "第66展厅",
"Visit Room 66": "参观第66展厅",
"White porcelain 'moon jar', Choson dynasty, Korea, 17-18th Century AD.": "白瓷“月亮罐”，朝鲜王朝，朝鲜半岛，公元17–18世纪。",
"Korea": "韩国",
"Room 67": "第67展厅",
"(The Korea Foundation Gallery)": "（韩国国际交流财团展厅）",
"Visit Room 67": "参观第67展厅",
"A penny with the words \"votes for women\" defaced across the Kings head.": "一枚便士硬币，国王头像上被刻上了“给妇女投票权”字样。",
"Money": "货币",
"Room 68": "第68展厅",
"Visit Room 68": "参观第68展厅",
"Bronze gladiator's helmet": "青铜角斗士头盔",
"Greek and Roman life": "希腊与罗马人的生活",
"Room 69": "第69展厅",
"Visit Room 69": "参观第69展厅",
"portland vase white relief figures on a black background": "波特兰花瓶：黑色底上的白色浮雕人物",
"Room 70 (": "第70展厅 (",
"The Wolfson Gallery": "沃尔夫森展厅",
"Painted sarcophagus of Seianti Hanunia Tlesnasa, Etruscan, 150-140 BC.": "塞安蒂·哈努尼亚·特勒斯纳萨彩绘石棺，伊特鲁里亚，公元前150–前140年。",
"Etruscan world": "伊特鲁里亚世界",
"Room 71": "第71展厅",
"Visit Room 71": "参观第71展厅",
"Red Polished Ware figurine cradling a child, Cypriot, 1975-1850 BC": "怀抱婴儿的红色磨光陶俑，塞浦路斯，公元前1975–前1850年",
"Ancient Cyprus": "古代塞浦路斯",
"Room 72 (": "第72展厅 (",
"The A.G. Leventis Gallery": "A.G.莱文蒂斯展厅",
"Visit Room 72": "参观第72展厅",
"Gold libation bowl (phiale) with six bulls around 600 BC, Western Greek.": "饰有六头公牛的黄金祭酒碗（菲阿勒），约公元前600年，西希腊。",
"Greeks in Italy": "意大利的希腊人",
"Room 73": "第73展厅",
"Visit Room 73": "参观第73展厅",
"A scene of shepherds and animals, and a woman on a horse, depicted in red-brown oil paint.": "以红棕色油彩描绘的牧人、牲畜和一位骑马女子的场景。",
"Prints and drawings displays": "版画与素描展",
"Rooms 90 and 90a": "第90和90a展厅",
"Visit Rooms 90 and 90a": "参观第90和90a展厅",
"Two red, white, blue and gold decorated mantelpiece elephants figures.": "两尊红、白、蓝、金四色装饰的壁炉摆件大象。",
"Japan": "日本",
"Rooms 92–94 (": "第92–94展厅 (",
"The Mitsubishi Corporation Japanese Galleries": "三菱商事日本展厅",
"Visit Rooms 92–94": "参观第92–94展厅",
"Two identical porcelain vases with blue details including dragon.": "一对相同的瓷瓶，饰有包括龙纹在内的青色纹样。",
"Chinese Ceramics – Sir Percival David Collection": "中国陶瓷——大维德爵士收藏",
"Room 95 (": "第95展厅 (",
"The Sir Joseph Hotung Centre for Ceramic Studies": "何鸿卿爵士陶瓷研究中心",
"Visit Room 95": "参观第95展厅",
"Red mask made from fibre glass, polyester resin, ply and balsar wood and bamboo,": "以玻璃纤维、聚酯树脂、胶合板、轻木和竹子制成的红色面具，",
"Virtual gallery": "虚拟展厅",
"Explore the Oceania collection": "探索大洋洲藏品",
"Drawing of boats sailing on rough seas": "描绘船只在惊涛骇浪中航行的素描",
"Prints and drawings": "版画与素描",
"Explore the Prints and drawings collection": "探索版画与素描藏品",

# ---------- newsletter / related ----------
"Sign up to our newsletters": "订阅我们的新闻通讯",
"Stay connected and receive all our latest news, stories and ways to visit the British Museum from home.": "与我们保持联系，获取最新资讯、故事以及足不出户游览大英博物馆的方式。",
"Sign Up": "立即订阅",
"You may also be interested in": "您可能还感兴趣",
"Stone panel fragment from the South-West Palace of Sennacherib, Assyria": "辛那赫里布西南宫石板残片，亚述",
"From building projects to military campaigns, learn about Nineveh – the capital of the Assyrian empire.": "从建筑工程到军事征伐，了解亚述帝国的首都——尼尼微。",
"Visitor looking at various sketches in Prints and Drawings": "在版画与素描展厅观看各类素描的参观者",
"Prints and drawings galleries 90 and 90a": "版画与素描展厅（第90和90a展厅）",
"Exhibitions and displays of Prints and Drawings from old masters to living artists": "从古代大师到当代艺术家的版画与素描展览和陈列",
"The marble sculptures that form the Parthenon": "构成帕特农神庙的大理石雕塑",
"The Parthenon was built as a temple dedicated to the goddess Athena.": "帕特农神庙是为供奉女神雅典娜而建造的神庙。",
"Marvel at the frieze, which was created to decorate the interior of the Temple of Apollo Epikourios at Bassae, in Room 16.": "在第16展厅欣赏这条饰带，它原本用于装饰巴赛的阿波罗·伊壁鸠鲁神庙内部。",
"Back to the top": "返回顶部",

# ---------- footer ----------
"Connect with us": "关注我们",
"Enter your email address to receive our newsletter": "输入您的电子邮箱地址以订阅新闻通讯",
"Sign up": "订阅",
"- opens in a new window": "- 在新窗口中打开",
"Facebook": "Facebook",
"X (formerly Twitter)": "X（原Twitter）",
"Instagram": "Instagram",
"Youtube": "YouTube",
"weibo": "微博",
"wechat": "微信",
". Opens a pop-up detailing how to access wechat.": "。打开弹窗，查看如何访问微信。",
"Close modal": "关闭弹窗",
"Close": "关闭",
"Scan the QR code to be taken to WeChat.": "扫描二维码前往微信。",
"A QR code that directs to WeChat.": "跳转至微信的二维码。",
"Free entry": "免费入场",
"Great Russell Street": "大罗素街（Great Russell Street）",
"London WC1B 3DG": "伦敦 WC1B 3DG",
"Box Office": "票务处",
"Opening hours": "开放时间",
"Daily: 10.00–17.00 (Fridays: 20.30)": "每日：10:00–17:00（周五至20:30）",
"Last entry: 16.45 (Fridays: 20.15)": "最晚入场：16:45（周五为20:15）",
"Footer": "页脚",
"About us": "关于我们",
"Governance": "治理",
"The British Museum story": "大英博物馆的故事",
"Jobs": "工作机会",
"Press": "新闻中心",
"Contact us": "联系我们",
"Audio guide": "语音导览",
"Commercial": "商业服务",
"Venue hire": "场地租赁",
"Filming": "影视拍摄",
"BM Images": "大英博物馆图片库",
"Licensing": "授权许可",
"Publishing": "出版",
"Travel trade tours": "旅游业团队参观",
"Our work": "我们的工作",
"Departments": "部门",
"National": "英国国内",
"International": "国际",
"How to borrow": "如何借展",
"Research": "研究",
"Research projects": "研究项目",
"Research publications": "研究出版物",
"Scientific studies": "科学研究",
"Resources": "资源",
"Study rooms": "研究室",
"Library and archive": "图书馆与档案馆",
"Search the collection": "检索馆藏",
"Footer Legal Links": "页脚法律链接",
"Privacy policy": "隐私政策",
"Cookies": "Cookie政策",
"Accessibility statement": "无障碍声明",
"Terms of use": "使用条款",
"Modern Slavery Act Statement": "《现代奴隶制法案》声明",
"Chinese site 中文": "中文网站",
"The Trustees of the British Museum": "大英博物馆理事会",
"Image lightbox": "图片灯箱",
"Close lightbox (Escape)": "关闭灯箱（Esc键）",
"Share": "分享",
"Toggle fullscreen": "切换全屏",
"Zoom in/out": "放大/缩小",
"Previous image": "上一张图片",
"Next image": "下一张图片",

# ---------- shared gallery-page elements ----------
"Take a virtual tour": "虚拟参观",
"Highlights": "精选展品",
"Visiting the gallery": "参观本展厅",
"Daily: 10.00–17.00 (": "每日：10:00–17:00 (",
"Fridays: 20.30": "周五至20:30",
"Advance booking advised": "建议提前预约",
"Gallery audio guides": "展厅语音导览",
"Listen on the": "可通过",
", available on the": "收听，该应用已上架",
"App Store": "App Store",
"Google Play": "Google Play",
"Plan and book your visit": "规划并预约参观",
"View family activity": "查看家庭活动",
"© The Trustees of the British Museum": "© 大英博物馆理事会",
"Virtual tour": "虚拟导览",
"Gallery facts": "展厅知识",
"Some objects in this collection feature on the British Sign Language multimedia guide. This resource is temporarily unavailable. You can access a selection of": "此展厅的部分展品收录于英国手语多媒体导览中，该资源暂时无法使用。您可以在自己的设备上观看精选的",
"BSL films": "英国手语视频",
"on your own device.": "。",
"Some objects in this collection feature on the audio description guide, available on": "此展厅的部分展品收录于口述影像导览中，可在以下平台收听：",
"Soundcloud": "Soundcloud",
"Seating is available.": "展厅内设有座椅。",
"Step-free access.": "提供无台阶通道。",
"British Museum Sensory Map (PDF)": "大英博物馆感官地图（PDF）",
"View sensory map": "查看感官地图",
"Access": "无障碍",
"Accessibility at the Museum": "博物馆无障碍服务",
"for more information.": "了解更多信息。",
"A man uses the audio guide in the Great Court": "一名男子在大中庭使用语音导览",
"Please note due to essential maintenance works there will be no lift or level access until late September. We apologise for any inconvenience caused during your visit.": "请注意，由于必要的维护工程，9月下旬前将无法使用电梯和无台阶通道。对于给您参观带来的不便，我们深表歉意。",

# ---------- Enlightenment (Room 1) ----------
"A young visitor looking at the display objects": "一位正在观看展品的年轻参观者",
"Visitor in Room 1. © The Trustees of the British Museum": "第1展厅中的参观者。© 大英博物馆理事会",
"Find Room 1": "查找第1展厅位置",
"Learn about the 18th century, an era of new knowledge, scientific discovery, European colonialism and the transatlantic slave trade.": "了解18世纪——一个充满新知识与科学发现，同时也伴随着欧洲殖民主义和跨大西洋奴隶贸易的时代。",
"The Enlightenment is the name given to a period of discovery and learning that flourished among Europeans and Americans from about 1680–1820, changing the way they viewed the world. This was also a time when Britain became a global power and grew wealthy. A significant part of that wealth came from Britain's colonial empire and its active involvement in the transatlantic slave trade.":
    "启蒙运动是指约1680年至1820年间在欧洲人和美洲人中间兴盛的一段探索与求知的时期，它改变了人们看待世界的方式。这一时期，英国也成为了世界强国并积累了大量财富，而其中相当一部分财富来自英国的殖民帝国及其对跨大西洋奴隶贸易的积极参与。",
"Housed in the oldest room in the present Museum – originally designed to house King George III's Library – this diverse permanent exhibition shows how British people understood the world at this time through their collections. The displays convey a sense of how objects were organised and displayed during the 18th century. Sir Hans Sloane's collection, with several additional libraries and collections, became the foundation of the British Museum, which was established on 7 June 1753 by an Act of Parliament.":
    "这一内容丰富的常设展览位于博物馆现存最古老的展厅内——该展厅最初是为收藏国王乔治三世的藏书而设计的。展览通过当时的收藏，展示了英国人在这一时期如何认识世界，并呈现出18世纪文物的整理与陈列方式。汉斯·斯隆爵士的收藏，连同其他几批藏书与藏品，共同奠定了大英博物馆的基础。1753年6月7日，大英博物馆依据议会法案正式成立。",
"While Enlightenment thinking and collections provided the foundations for much of our present understanding of the history of human cultural achievement, they also tended to tell that story from a predominantly European perspective. This period, and its legacies, are now increasingly being reassessed from a range of critical perspectives.":
    "启蒙思想和启蒙时代的收藏为我们今天理解人类文化成就史奠定了重要基础，但它们往往也主要是从欧洲视角来讲述这段历史。如今，人们正越来越多地从多种批判性视角重新审视这一时期及其遗产。",
"Explore the grandeur of the": "领略",
"Enlightenment gallery": "启蒙运动展厅",
". Peer into the display cases that line the walls to find a fascinating and eclectic collection that inspired an age.": "的恢弘气势。细看沿墙排列的展柜，发现一批启迪了整个时代、引人入胜又包罗万象的藏品。",
"A view along the length of the Enlightenment gallery. ©2020 Google.": "沿启蒙运动展厅纵向望去的景象。©2020 Google。",
"Legacies of empire and slavery": "帝国与奴隶制的遗产",
"The Age of Enlightenment was characterised by the rise of new sciences, faith in reason and expanding trade. It also witnessed the aggressive global expansion of European colonialism and the transatlantic slave trade. This room's displays reflect the close connection between Enlightenment and empire.":
    "启蒙时代的特征是新科学的兴起、对理性的信仰以及贸易的扩张。与此同时，这个时代也见证了欧洲殖民主义和跨大西洋奴隶贸易在全球范围内的激进扩张。本展厅的陈列反映了启蒙运动与帝国之间的紧密联系。",
"From the late 16th century onwards, Britain was one of the main participants in the transatlantic slave trade along with other European countries, transporting people against their will from West Africa to work on plantations in the Americas, then bringing goods and wealth back to Europe. This trade was at its height during the 18th century. Millions of Africans were enslaved, many working in brutal conditions on hugely profitable sugar plantations.":
    "从16世纪晚期开始，英国与其他欧洲国家一道，成为跨大西洋奴隶贸易的主要参与者之一：他们违背人们的意愿，将其从西非运往美洲的种植园劳作，再把商品和财富运回欧洲。这一贸易在18世纪达到顶峰。数以百万计的非洲人沦为奴隶，其中许多人在利润丰厚的甘蔗种植园里忍受着残酷的劳作条件。",
"The slave trade was abolished by Parliament in 1807 and the Slavery Abolition Act of 1833 led to the end of slave ownership in most British colonies. Abolition was motivated by passionately disputed religious and moral arguments, but also by the declining profitability of slave-based labour and the increasing impact of slave rebellions, most notably the Haitian Revolution of 1791 and the 1831 Jamaica rebellion. British slave owners were compensated financially for the loss of what was regarded as their 'property'.":
    "1807年，英国议会废除了奴隶贸易；1833年的《废除奴隶制法案》则终结了英国大部分殖民地的奴隶所有制。推动废奴的，既有激烈争论中的宗教与道德主张，也有奴隶劳动利润的下降以及奴隶起义日益增长的影响，其中最著名的是1791年的海地革命和1831年的牙买加起义。英国奴隶主因失去被视为其“财产”的奴隶而获得了经济补偿。",
"1 of 7": "第1张，共7张",
"Image 1 of 7": "第1张图片，共7张",
"Image 2 of 7": "第2张图片，共7张",
"Image 3 of 7": "第3张图片，共7张",
"Image 4 of 7": "第4张图片，共7张",
"Image 5 of 7": "第5张图片，共7张",
"Image 6 of 7": "第6张图片，共7张",
"Image 7 of 7": "第7张图片，共7张",
"Bust of Sir Hans Sloane, 18th century - select to view a larger version of this image. Opens in a lightbox dialog.": "汉斯·斯隆爵士半身像，18世纪——点击查看大图，将在灯箱对话框中打开。",
"Terracotta bust of Sir Hans Sloane": "汉斯·斯隆爵士赤陶半身像",
"Bust of Sir Hans Sloane, 18th century": "汉斯·斯隆爵士半身像，18世纪",
"Portrait of Ayuba Suleiman Diallo, 1734 - select to view a larger version of this image. Opens in a lightbox dialog.": "阿尤巴·苏莱曼·迪亚洛肖像，1734年——点击查看大图，将在灯箱对话框中打开。",
"Printed portrait of Ayuba Suleiman Diallo": "阿尤巴·苏莱曼·迪亚洛版画肖像",
"Portrait of Ayuba Suleiman Diallo, 1734": "阿尤巴·苏莱曼·迪亚洛肖像，1734年",
"Shield from New South Wales, Australia, around 18–19th century - select to view a larger version of this image. Opens in a lightbox dialog.": "盾牌，澳大利亚新南威尔士州，约18–19世纪——点击查看大图，将在灯箱对话框中打开。",
"View of front of aboriginal bark shield": "原住民树皮盾牌正面",
"Shield from New South Wales, Australia, around 18–19th century": "盾牌，澳大利亚新南威尔士州，约18–19世纪",
"Piranesi vase, AD 100–200 and AD 1770s - select to view a larger version of this image. Opens in a lightbox dialog.": "皮拉内西花瓶，公元100–200年及18世纪70年代——点击查看大图，将在灯箱对话框中打开。",
"The ornate Piranesi vase from the Enlightenment gallery": "启蒙运动展厅中华丽的皮拉内西花瓶",
"Piranesi vase, AD 100–200 and AD 1770s": "皮拉内西花瓶，公元100–200年及18世纪70年代",
"The Sloane Astrolabe, AD 1290–1300 - select to view a larger version of this image. Opens in a lightbox dialog.": "斯隆星盘，公元1290–1300年——点击查看大图，将在灯箱对话框中打开。",
"The Sloane Astrolabe, part of the British Museum's founding collection": "斯隆星盘，大英博物馆创馆藏品之一",
"The Sloane Astrolabe, AD 1290–1300": "斯隆星盘，公元1290–1300年",
"Cista mystica (‘casket used in the mysteries’), BC 299–200 - select to view a larger version of this image. Opens in a lightbox dialog.": "神秘仪式箱（“秘仪中使用的匣子”），公元前299–前200年——点击查看大图，将在灯箱对话框中打开。",
"Container for cosmetic articles.": "盛放化妆用品的容器。",
"Bronze container for cosmetic items": "青铜化妆品盒",
", from the collection of Charles Townley.": "，出自查尔斯·汤利的收藏。",
"Cista mystica (‘casket used in the mysteries’), BC 299–200": "神秘仪式箱（“秘仪中使用的匣子”），公元前299–前200年",
"The Merman, AD 1700–1799 - select to view a larger version of this image. Opens in a lightbox dialog.": "人鱼标本，公元1700–1799年——点击查看大图，将在灯箱对话框中打开。",
"The Mermaid, a creature made of a dried fish and dried monkey fused together with wood. The Victorians thought it was real.": "“美人鱼”：用风干的鱼和风干的猴子以木料拼接而成的生物，维多利亚时代的人们曾以为它是真的。",
"The Merman, AD 1700–1799": "人鱼标本，公元1700–1799年",
"Seven major disciplines of the Enlightenment age": "启蒙时代的七大学科",
"The natural world": "自然世界",
"In the 18th century, the collections were divided into 'Natural and Artificial Rarities' – objects found in nature or made by people. Only a few rooms in the early Museum had manmade objects but case after case was filled with natural specimens from Sloane's collection and his library which included the 265 volumes of his herbarium.":
    "18世纪时，藏品被分为“自然珍奇”与“人工珍奇”两类——即自然界中发现的物品和人类制作的物品。早期博物馆中只有少数几个展厅陈列人造物品，而一个又一个展柜里摆满了斯隆收藏中的自然标本，以及他的藏书，其中包括265卷植物标本集。",
"In 1735, the Swedish botanist Carl Linnaeus revolutionised the way plants, animals and other objects from the natural world were named and classified. His pupil, Daniel Solander, was a curator in the Museum and applied the system to Sloane's collections and to the natural history specimens Solander himself collected with Sir Joseph Banks on the first Cook voyage.":
    "1735年，瑞典植物学家卡尔·林奈彻底革新了植物、动物以及自然界其他物体的命名和分类方式。他的学生丹尼尔·索兰德曾任博物馆馆员，他将这一体系应用于斯隆的藏品，以及他本人在库克船长第一次航行中与约瑟夫·班克斯爵士一同采集的自然历史标本。",
"Many of these original specimens are included in the exhibition, as well as a number of fossils. By 1880 there were so many natural history specimens that they needed a museum of their own – the Natural History Museum in South Kensington.":
    "展览中陈列了许多当年的原始标本以及一些化石。到1880年，自然历史标本的数量已多到需要一座专门的博物馆来收藏——这就是位于南肯辛顿的自然历史博物馆。",
"Fruit and flowers on a green leaf plant.": "绿叶植物上的果实与花朵。",
"Plant collage by Botanist, Mary Delany": "植物学家玛丽·德拉尼的植物拼贴画",
"The birth of archaeology": "考古学的诞生",
"Antiquaries collected books, manuscripts, drawings and artefacts from the past, and travelled the country studying ruins in order to learn more about Britain's Roman past and its earlier history.":
    "古物学家收集古代的书籍、手稿、图画和器物，并走遍全国考察遗迹，以进一步了解不列颠的罗马时期及更早的历史。",
"It was fairly easy to learn about medieval times because many of these objects had survived, including religious artefacts, armour, books and buildings. But antiquaries also began to survey and map Roman and earlier sites, such as Stonehenge, in a more scientific and systematic way and to learn more about the earliest Britons.":
    "了解中世纪相对容易，因为许多那个时代的物品都保存了下来，包括宗教器物、盔甲、书籍和建筑。但古物学家也开始以更科学、更系统的方式对罗马时期及更早的遗址（如巨石阵）进行勘测和绘图，以更多地了解最早的不列颠人。",
"This knowledge, combined with the new study of rock strata, led archaeologists to question the accepted date of the world's creation – 4004 BC – calculated from readings of the Bible.":
    "这些知识与新兴的岩层研究相结合，使考古学家开始质疑根据《圣经》推算出的、公认的世界创造年代——公元前4004年。",
"A Palaeolithic handaxe made from flint.": "燧石制成的旧石器时代手斧。",
"Grays Inn hand axe": "格雷律师学院路手斧",
"Art and civilisation": "艺术与文明",
"In 1824, Charles Townley's famous collection of Greek and Roman sculptures, acquired on his Grand Tours in Italy, came to the British Museum. They joined the collections of prints and drawings, gems, coins, bronzes, vases and other classical antiquities from fellow connoisseurs such as Sir William Hamilton and Richard Payne Knight.":
    "1824年，查尔斯·汤利在意大利“大旅行”期间收集的著名希腊罗马雕塑藏品入藏大英博物馆。与之汇聚一堂的，还有威廉·汉密尔顿爵士、理查德·佩恩·奈特等鉴赏家同好收藏的版画与素描、宝石、钱币、青铜器、陶瓶及其他古典文物。",
"These men studied each other's collections to learn about the 'progress' of art, from 'primitive' beginnings in early civilisations to what they considered to be the height of artistic achievement – the sculpture and architecture of classical Greece.":
    "这些人相互研究彼此的收藏，以了解艺术的“进步”——从早期文明中“原始”的开端，到他们心目中艺术成就的巅峰：古典希腊的雕塑与建筑。",
"This became the standard against which to measure all art and led, in late 18th-century Britain, to a classical revival in architecture and the decorative arts.":
    "这成为了衡量一切艺术的标准，并在18世纪晚期的英国引发了建筑和装饰艺术领域的古典复兴。",
"Watercolour drawing including Hindu, Mexican, Honduran, Assyrian, Egyptian and Greek art": "一幅水彩画，描绘了印度教、墨西哥、洪都拉斯、亚述、埃及和希腊的艺术品",
"James Stephanoff,": "詹姆斯·斯蒂芬诺夫，",
"An Assemblage of Works of Art": "《艺术品汇集》",
", from the Earliest Period to the Time of Phydias, a watercolour.": "（从最早时期到菲狄亚斯时代），水彩画。",
"Classifying the world": "为世界分类",
"Everything gathered in the 18th century had to be classified and organised so that it could be more easily understood and used.": "18世纪收集的一切都必须经过分类和整理，以便更容易被理解和利用。",
"King George III's library was presented to the nation by George IV and was housed in the room that is now the Enlightenment Gallery (his library is now in the British Library). The coins and medals collection was among the first part of the library to arrive at the Museum and they were arranged by country and ruler to help bring past history alive. George III was also keenly interested in the navy, navigation and scientific discoveries and collected instruments and working models.":
    "国王乔治三世的藏书由乔治四世献给国家，存放在如今的启蒙运动展厅中（这批藏书现藏于大英图书馆）。钱币与奖章收藏是最早运抵博物馆的部分之一，它们按国家和统治者排列，让过去的历史变得生动鲜活。乔治三世还对海军、航海和科学发现抱有浓厚兴趣，收藏了许多仪器和可运转的模型。",
"Sir William Hamilton arranged his vases found in the area around Naples according to the styles of painting, attempting to establish a chronology for them. He later published them in beautifully illustrated folios.":
    "威廉·汉密尔顿爵士按照绘画风格整理他在那不勒斯周边地区发现的陶瓶，试图为它们建立年代序列。后来，他将这些陶瓶编成了插图精美的对开本图册出版。",
"In the early part of the century, Sir Hans Sloane filled his cabinets with curious 'artificial' (manmade) objects from around the world, including those collected from enslaved peoples in Jamaica. These objects were catalogued and displayed in many different ways – by type, material, date or purpose.":
    "18世纪初，汉斯·斯隆爵士的珍奇柜里摆满了来自世界各地的奇特“人工”（人造）物品，其中包括从牙买加被奴役民族那里收集来的物品。这些物品以多种方式编目和陈列——按类型、材质、年代或用途分类。",
"Golden astrolabe made of brass.": "黄铜制成的金色星盘。",
"The Sloane Astrolabe": "斯隆星盘",
", England, 1290–1300.": "，英格兰，1290–1300年。",
"Ancient scripts": "古代文字",
"The Enlightenment led to a fevered interest in deciphering the mysterious forms of Egyptian hieroglyphs and the cuneiform inscriptions found in lands described in the Bible as well as early forms of Sanskrit in India.":
    "启蒙运动激发了人们破译神秘文字的狂热兴趣：埃及象形文字、在《圣经》所描述的土地上发现的楔形文字铭文，以及印度早期形式的梵文。",
"Scholars 'cracked the codes' in the 19th century, opening up thousands of years of history.": "学者们在19世纪“破解了密码”，揭开了数千年的历史。",
"At the same time, antiquaries deciphered runes and other early forms of writing, revealing more of our own history. This was a period when significant numbers of antiquities, acquired from collectors, diplomats and through excavation, entered the British Museum.":
    "与此同时，古物学家破译了卢恩文字和其他早期文字，揭示了更多关于我们自身的历史。在这一时期，大量从收藏家、外交官手中获得或经由发掘所得的古物进入了大英博物馆。",
"A letter written in English with hieroglyphics at the bottom": "一封用英文书写、底部附有象形文字的信",
"A letter from Thomas Young (1773–1829), the English polymath who had been trying to decipher ancient Egyptian hieroglyphs since the French army discovered the Rosetta Stone in 1799.":
    "托马斯·杨（1773–1829）的一封信。这位英国博学家自1799年法国军队发现罗塞塔石碑以来，一直致力于破译古埃及象形文字。",
"Ritual and religion": "仪式与宗教",
"Christian mistrust of superstition and idols, rituals and magic led to ignorance about other religions.": "基督教对迷信、偶像、仪式和巫术的不信任，导致人们对其他宗教缺乏了解。",
"Enlightenment scholars attempted to dispel this by studying the ancient and modern religions they encountered. They researched rituals and cults in different cultures, collected religious artefacts, grouped gods into families and examined their attributes and functions.":
    "启蒙时代的学者试图通过研究他们所接触到的古代和现代宗教来消除这种无知。他们研究不同文化中的仪式和崇拜，收集宗教器物，将诸神归入不同的神系，并考察其属性和职能。",
"They wanted to find similarities that might shed light on the origins of the world's religions. Much of this activity took place within the context of colonialism.": "他们希望找到能够揭示世界各宗教起源的相似之处。而这些活动大多是在殖民主义的背景下进行的。",
"Trade and discovery": "贸易与发现",
"In this era of colonialism and global trade, travellers, traders, scientists, explorers and diplomats created collections of ethnographic objects, including ceremonial and everyday items, thought representative of customs and cultures of people around the globe. They collected artefacts and published illustrated accounts about the lives and cultures of people around the world, from a European perspective.":
    "在这个殖民主义与全球贸易的时代，旅行者、商人、科学家、探险家和外交官建立起民族志藏品收藏，其中包括仪式用品和日常用品，这些物品被认为代表了全球各地民族的风俗与文化。他们从欧洲视角出发，收集器物，并出版了关于世界各地人民生活与文化的图文记述。",
"Alongside Sir Hans Sloane's collection, the British Museum also houses objects from the voyages of Captain James Cook and Sir Joseph Banks to Australia, New Zealand, Tahiti and other Pacific islands. A significant number of objects were acquired through employees of the East India and Royal Africa Companies, whose wealth was made possible through the use of enslaved labour and the exploitation of people and resources.":
    "除汉斯·斯隆爵士的收藏外，大英博物馆还收藏有詹姆斯·库克船长和约瑟夫·班克斯爵士航行至澳大利亚、新西兰、塔希提及其他太平洋岛屿时获得的物品。相当多的藏品是通过东印度公司和皇家非洲公司的雇员获得的，而这些公司的财富正是建立在使用奴隶劳动、剥削人民与资源的基础之上。",
"Print portrait of Captain James Cook": "詹姆斯·库克船长版画肖像",
"Portrait of Captain James Cook": "詹姆斯·库克船长肖像",
", print on paper made by John Keyse Sherwin, Britain, 1784.": "，约翰·凯斯·舍温制作的纸本版画，英国，1784年。",

# Enlightenment lightbox captions
"Hans Sloane (1660–1753), whose collection was purchased for the public to found the British Museum, acquired objects and natural specimens during his time in Jamaica as physician to the British Governor of the island. He would later become physician to Kings George I and II, and President of the Royal Society. This bust was made by Michael Rysbrack in the 1730s as a model for a full-length marble sculpture of Sloane.":
    "汉斯·斯隆（1660–1753）的收藏被购为公共所有，奠定了大英博物馆的基础。他在担任英国驻牙买加总督的私人医生期间获得了许多物品和自然标本，后来又成为国王乔治一世和乔治二世的御医，并出任英国皇家学会会长。这尊半身像由迈克尔·里斯布拉克于18世纪30年代制作，是一尊斯隆全身大理石雕像的模型。",
"Together with his medical earnings and land investments, Sloane used income generated by enslaved people on plantations, inherited by his wife Elizabeth Langley Rose Sloane, to purchase 'curiosities' from around the expanding British empire and his wide network of contacts around the globe.":
    "除了行医收入和土地投资外，斯隆还利用其妻子伊丽莎白·兰利·罗斯·斯隆继承的种植园中被奴役者所创造的收入，通过不断扩张的大英帝国以及他遍布全球的人脉网络购买“珍奇之物”。",
"Belonging to a Senegalese family of Muslim clerics, Diallo was sold into slavery in West Africa in 1731. Captured while trading slaves for his father, he was transported to work on a plantation in Maryland, America. Diallo was brought to London in 1733 and while there translated the inscriptions on Hans Sloane's collection of Islamic amulets (now in the British Museum). Diallo was bought out of slavery by public subscription and returned to West Africa.":
    "迪亚洛出身于塞内加尔一个穆斯林教士家庭，1731年在西非被卖为奴隶。他在替父亲进行奴隶交易时被俘，随后被运往美洲马里兰的一个种植园劳作。1733年，迪亚洛被带到伦敦，并在那里翻译了汉斯·斯隆所藏伊斯兰护身符上的铭文（这些护身符现藏于大英博物馆）。后来，人们通过公众募捐为他赎身，他得以返回西非。",
"Little is known of his later years before his death in 1773. Advocates of the abolition of slavery cited Diallo as a key figure in their assertion of the moral rights and humanity of Black people. This etching by William Hoare is based on his 1733 oil painting of Diallo wearing a copy of the Qur'an.":
    "人们对他在1773年去世前的晚年生活知之甚少。废奴主义者将迪亚洛视为关键人物，以此论证黑人的道德权利与人性。这幅蚀刻版画由威廉·霍尔创作，底本是他1733年绘制的油画，画中的迪亚洛佩戴着一部《古兰经》。",
"Shield from New South Wales, Australia, around 18–19th century.": "盾牌，澳大利亚新南威尔士州，约18–19世纪。",
"This shield, of bark and wood (red mangrove), dates to the late 1700s or early 1800s. Broad shields such as this were used as defensive weapons against spears. The size and shape of the hole in this shield suggest it was pierced by a spear.":
    "这面盾牌由树皮和木材（红树）制成，年代为18世纪晚期或19世纪初期。这类宽大的盾牌用作抵御长矛的防御武器。从盾上孔洞的大小和形状来看，它曾被长矛刺穿。",
"Although once thought to have been collected in 1770 by James Cook or Joseph Banks at Kamay (Botany Bay, near Sydney), it may have been obtained from its owner between about 1790 and 1815 and sent to London by a colonial governor or other collector.":
    "尽管人们曾认为它是1770年由詹姆斯·库克或约瑟夫·班克斯在卡迈（悉尼附近的植物学湾）收集的，但它也可能是在约1790年至1815年间从其主人手中获得，再由某位殖民地总督或其他收藏者寄往伦敦的。",
"It is the earliest known Aboriginal shield from Australia and has come to symbolise the first British colonization of Australia and its ongoing legacy, which still affects Aboriginal and Torres Strait Islander people in Australia today.":
    "这是已知最早的澳大利亚原住民盾牌，它已成为英国首次殖民澳大利亚及其持续影响的象征——这种影响至今仍作用于澳大利亚的原住民和托雷斯海峡岛民。",
"Read more about the shield and discussions around this object": "进一步了解这面盾牌及围绕它的讨论",
"Renowned Italian architect and engraver, Giovanni Battista Piranesi (1720–1778), also restored and sold ancient marbles. This ornamental vase combines expertly restored fragments of a figurative frieze of satyrs at a vintage, discovered in the villa of Roman emperor, Hadrian (AD 117–138).":
    "著名的意大利建筑师和版画家乔瓦尼·巴蒂斯塔·皮拉内西（1720–1778）也从事古代大理石雕刻的修复和买卖。这只装饰花瓶融合了经过精心修复的残片，残片上是萨提尔们采摘葡萄的人物饰带，发现于罗马皇帝哈德良（公元117–138年在位）的别墅中。",
"This large and stunning Astrolabe was made in mediaeval England and is part of our founding collection, belonging to Sir Hans Sloane. Highly sophisticated, an astrolabe can enable the user to tell the time in different hour systems, day and night, to establish heights and angles and to facilitate the casting of horoscopes.":
    "这件巨大而令人惊叹的星盘制作于中世纪的英格兰，原属汉斯·斯隆爵士，是本馆的创馆藏品之一。星盘是一种极为精密的仪器，使用者可以借助它在白天和夜晚以不同的计时体系报时、测定高度和角度，还可以用来推算星象。",
"Cista mystica ('casket used in the mysteries'), BC 299–200": "神秘仪式箱（“秘仪中使用的匣子”），公元前299–前200年",
"The collector Charles Townley (1753–1805), thought that the scenes engraved on it indicated that such boxes were used in the Mysteries of Dionysos and the Eleusinian Mysteries. In fact it's simply a container for cosmetic articles.":
    "收藏家查尔斯·汤利（1753–1805）认为，盒上雕刻的场景表明这类盒子曾用于狄俄尼索斯秘仪和厄琉息斯秘仪。而实际上，它只是一个盛放化妆用品的容器。",
"The merman is made up of the dried upper parts of a monkey, with a fishtail. 'Caught' in the sea off Japan, this kind of curiosity was found in early cabinets before a more reasoned approach to collecting evolved in the 1700s.":
    "这件人鱼标本由风干的猴子上半身和一条鱼尾拼接而成，据称“捕获”于日本近海。在18世纪更为理性的收藏方式形成之前，这类奇物常见于早期的珍奇柜中。",
"Bronze container for cosmetic items, from the collection of Charles Townley.": "青铜化妆品盒，出自查尔斯·汤利的收藏。",

# ---------- Africa (Room 25) ----------
"Please note that due to regular maintenance works Room 25 will be closed on 22 September 2026.": "请注意，由于例行维护工作，第25展厅将于2026年9月22日关闭。",
"alert": "提示",
"Room 25": "第25展厅",
"The Benin Bronze plaques in the Africa gallery.": "非洲展厅中的贝宁青铜饰板。",
"The Benin Bronze plaques on Collection online": "在线馆藏中的贝宁青铜饰板",
"Reopening on 23 September": "9月23日重新开放",
"Find Room 25": "查找第25展厅位置",
"The Africa Galleries reveal the extraordinary cultural, artistic and historical diversity and complexity of the continent represented by the collections.": "非洲展厅通过馆藏，展现了非洲大陆在文化、艺术和历史上非凡的多样性与复杂性。",
"The galleries present varied material and artistic traditions, including forged metalwork, textiles, pottery-making, masquerade and sculpture. Cross-cutting the displays, the galleries approach a range of wider themes, including trade, identity, gender, power, religion and transformation.":
    "展厅呈现了丰富多样的物质与艺术传统，包括锻造金属工艺、纺织品、制陶、假面舞会和雕塑。展厅还贯穿各个陈列，探讨了一系列更宏大的主题，包括贸易、身份、性别、权力、宗教与转变。",
"The inclusion of contemporary art throughout the galleries highlights the continuing vibrancy and relevance of art in and about Africa, both by artists living on the continent and those of African heritage working outside it. Among the contemporary art works represented there is a particular focus on artworks inspired or informed by earlier creative traditions.":
    "展厅各处都融入了当代艺术作品，彰显出非洲艺术以及关于非洲的艺术持久的活力与现实意义——这些作品既出自生活在非洲大陆的艺术家，也出自在非洲以外工作的非洲裔艺术家。在展出的当代艺术作品中，尤其突出那些受早期创作传统启发或影响的作品。",
"Take a virtual walk around the": "在",
"Africa galleries": "非洲展厅",
"and see the moving Throne of Weapons, made from decommissioned firearms from Mozambique's 17-year civil war.": "中进行一次虚拟漫步，观看令人动容的《武器王座》——它由莫桑比克17年内战中退役的枪支制成。",
"A display case and signage in the Africa galleries. ©2020 Google.": "非洲展厅中的展柜与标识。©2020 Google。",
"Bronze-casting dates back to at least the 9–10th centuries": "青铜铸造至少可以追溯到9–10世纪",
"in West Africa and casting in copper alloy remains a vibrant industry today. The collections from the Nigerian sites of Igbo-Ukwu, Ife, and Benin represent some of the most important early West African bronze-casting traditions and highlight the technical knowledge of metalworkers who used the lost-wax casting technique to create objects of great power and virtuosity.":
    "的西非，铜合金铸造至今仍是一个充满活力的行业。来自尼日利亚伊格博-乌库、伊费和贝宁等遗址的藏品，代表了西非早期最重要的一些青铜铸造传统，彰显了金属工匠们运用失蜡铸造法创造出极具力量与精湛技艺之作品的专业知识。",
"For at least 2,000 years,": "至少2000年来，",
"different types of looms, weaving technologies and raw materials have been used to create regionally distinctive cloths in African societies. Textiles communicate key information about communities and individuals through their designs, use and materials. They can be used to document significant historical events and may also chart the movements and migrations of people, markets and trading patterns.":
    "非洲社会一直使用不同类型的织机、织造技术和原材料，制作出具有鲜明地域特色的布料。纺织品通过其图案、用途和材料传达着有关群体与个人的重要信息。它们可以用来记录重大历史事件，也可能反映人口的流动与迁徙、市场以及贸易格局。",
"Africa is home to some of the oldest pottery making traditions in the world,": "非洲拥有世界上最古老的一些制陶传统，",
"including pottery found in excavations in West Africa (Mali) dating to at least 9,500 BC. Pottery traditions are found across the continent and include not only functional objects but also items of ritual or religious importance. Today, pottery-making continues to be an important means of artistic expression.":
    "其中包括在西非（马里）发掘出土、年代至少可追溯至公元前9500年的陶器。制陶传统遍布整个非洲大陆，其产物不仅有实用器物，也有具有仪式或宗教意义的物品。时至今日，制陶仍是一种重要的艺术表达方式。",
"Large wooden door with 10 scenes featuring human figures.": "刻有10幅人物场景的大型木门。",
"Carved wooden doors": "木雕门",
", by Olowe of Ise, Nigeria, early 20th century.": "，伊塞的奥洛维作品，尼日利亚，20世纪初。",
"Masquerade is both an art of performance and transformation in Africa.": "在非洲，假面舞既是一门表演艺术，也是一门转化的艺术。",
"Often, masquerades maintain and express the secret knowledge of local communities. They are danced at key moments, such as during initiation, at funerals, and to mark the agricultural calendar. Masquerade performance continues to be a predominantly male activity, although the characters may be female. Masquerade incorporates dancing, music and the participation of spectators.":
    "假面舞往往承载并表达着当地社群的秘传知识。人们会在一些关键时刻表演假面舞，例如成年礼、葬礼，以及标志农事历法的时节。假面舞表演至今仍主要由男性参与，尽管其中的角色可能是女性。假面舞融合了舞蹈、音乐以及观众的参与。",
"The identity of many of the historic artists": "许多历史上的艺术家",
"whose works are seen within the Africa galleries is often unknown. Among the historic artists represented within the galleries whose identity we do know is the celebrated Yoruba carver, Olowe of Ise. A pair of monumental carved doors by Olowe of Ise on display in the galleries previously featured within the 1924 Nigerian Pavilion at the British Empire Exhibition at Wembley, London.":
    "的作品陈列在非洲展厅中，但他们的身份往往无从知晓。在展厅中身份已知的历史艺术家里，有一位是著名的约鲁巴木雕大师——伊塞的奥洛维。展厅中陈列的一对由他创作的巨型木雕门，曾于1924年在伦敦温布利举办的大英帝国博览会尼日利亚馆中展出。",
"Every department in the Museum includes African objects in its collections.": "博物馆的每个部门都收藏有非洲文物。",
"A notable example of an African object displayed elsewhere within the Museum is 'the Akan Drum', currently on display in Room 26, the North American gallery and bequeathed by the Museum's founder, Sir Hans Sloane. Although the drum was acquired by Sloane in Virginia, USA, it had been made in Africa, almost certainly travelling to the Americas on a ship linked to the Transatlantic Slave Trade.":
    "陈列在博物馆其他展厅中的非洲文物，一个著名的例子是“阿坎鼓”。它目前在第26展厅（北美展厅）展出，由博物馆创始人汉斯·斯隆爵士遗赠。尽管这面鼓是斯隆在美国弗吉尼亚获得的，但它制作于非洲，几乎可以肯定是随一艘与跨大西洋奴隶贸易有关的船只来到美洲的。",
"For at least 2,000 years, different types of looms, weaving technologies and raw materials have been used to create regionally distinctive cloths in African societies.": "至少2000年来，非洲社会一直使用不同类型的织机、织造技术和原材料，制作出具有鲜明地域特色的布料。",
"1 of 6": "第1张，共6张",
"Image 1 of 6": "第1张图片，共6张",
"Image 2 of 6": "第2张图片，共6张",
"Image 3 of 6": "第3张图片，共6张",
"Image 4 of 6": "第4张图片，共6张",
"Image 5 of 6": "第5张图片，共6张",
"Image 6 of 6": "第6张图片，共6张",
"Brass head of an Ooni (king) of Ife - select to view a larger version of this image. Opens in a lightbox dialog.": "伊费奥尼（国王）黄铜头像——点击查看大图，将在灯箱对话框中打开。",
"Brass head wearing a crown.": "头戴王冠的黄铜头像。",
"Brass head of an Ooni (king) of Ife": "伊费奥尼（国王）黄铜头像",
"Salt-cellar (in three parts) made of ivory - select to view a larger version of this image. Opens in a lightbox dialog.": "象牙盐罐（由三部分组成）——点击查看大图，将在灯箱对话框中打开。",
"Ivory cellar with four European figures.": "饰有四个欧洲人形象的象牙盐罐。",
"Salt-cellar (in three parts) made of ivory": "象牙盐罐（由三部分组成）",
"Chair of Power - select to view a larger version of this image. Opens in a lightbox dialog.": "权力之椅——点击查看大图，将在灯箱对话框中打开。",
"Ebony chair with stringing design.": "带有镶线装饰的乌木椅。",
"Chair of Power": "权力之椅",
"Appliqué cotton tent panel (khiyamiya) - select to view a larger version of this image. Opens in a lightbox dialog.": "贴花棉布帐篷饰板（khiyamiya）——点击查看大图，将在灯箱对话框中打开。",
"Large orange tent-hanging with shapes and human and animal figures illustrated on it.": "绘有几何图形及人物和动物形象的大型橙色帐篷挂饰。",
"Appliqué tent-cloth": "贴花帐篷布",
", Cairo, 1928 (before).": "，开罗，1928年（或更早）。",
"Appliqué cotton tent panel (khiyamiya)": "贴花棉布帐篷饰板（khiyamiya）",
"Mask (kifwebe) - select to view a larger version of this image. Opens in a lightbox dialog.": "面具（kifwebe）——点击查看大图，将在灯箱对话框中打开。",
"A mask in three parts, straw like bottom, face and hair pieces.": "由三部分组成的面具：草状底部、面部和头发部分。",
"Mask (kifwebe)": "面具（kifwebe）",
"Tree of life - select to view a larger version of this image. Opens in a lightbox dialog.": "生命之树——点击查看大图，将在灯箱对话框中打开。",
"3.5m high tree made from weapons in the Africa gallery.": "非洲展厅中用武器制成的3.5米高的树。",
"Tree of life": "生命之树",

# Africa lightbox captions
"Brass head of an Ooni (king) of Ife, Nigeria 1300s – early 1400s": "伊费奥尼（国王）黄铜头像，尼日利亚，14世纪–15世纪初",
"This crowned head was discovered by accident in 1939 during digging close to the royal palace in Ife. Between 1100 and 1400 Ife was one of the great city-states in West Africa and flourished as a commercial centre within regional and long-distance trade networks.":
    "这件戴冠头像于1939年在伊费王宫附近施工挖掘时被偶然发现。1100年至1400年间，伊费是西非伟大的城邦之一，作为区域性和长途贸易网络中的商业中心而繁荣兴盛。",
"Salt cellar (in three parts) made of ivory. Benin, Nigeria": "象牙盐罐（由三部分组成），贝宁，尼日利亚",
"This salt cellar is made of ivory and represents Europeans, shown with long hair, beards and hooked noses. It was made by a master craftsperson in the Kingdom of Benin, Nigeria between 1525 – 1600. Africans along the continent's west coast first encountered Portuguese traders in the mid-15th century. This marked the beginning of regular contact and trade, during which the purchase and commissioning of carved ivory goods by Europeans became common. Such luxury items made as souvenirs are among the first-known examples of 'tourist art' from Africa.":
    "这件盐罐以象牙制成，刻画的是长发、蓄须、鹰钩鼻的欧洲人形象，由尼日利亚贝宁王国的一位工艺大师于1525年至1600年间制作。15世纪中叶，非洲西海岸的非洲人首次与葡萄牙商人相遇，由此开启了经常性的接触与贸易；在此期间，欧洲人购买和定制象牙雕刻制品的情况变得十分普遍。这类作为纪念品制作的奢侈品，是已知最早的非洲“旅游艺术品”之一。",
"This distinctive form of high-backed ebony chair with elaborate stringing and inset ivory panels highlights the participation of the islands off the East African coast within wider Indian Ocean trading networks. These so-called 'chairs of power' (kiti cha enzi), were used by wealthy families on Paté, Lamu and Zanzibar islands. They were reserved for the use of visiting guests, dignitaries and the most important family members.":
    "这种造型独特的高背乌木椅饰有精美的镶线和嵌入式象牙面板，反映了东非沿海岛屿对更广泛的印度洋贸易网络的参与。这些所谓的“权力之椅”（kiti cha enzi）为帕特岛、拉穆岛和桑给巴尔岛上的富裕家庭所用，专供来访宾客、显贵和最重要的家族成员使用。",
"Appliqué cotton tent panel (khiyamiya), Egypt, early 1900s": "贴花棉布帐篷饰板（khiyamiya），埃及，20世纪初",
"Large-scale colourful textiles such as this were used to create tents in towns and cities across Egypt to accommodate guests at weddings, funerals and other significant ceremonies. This hanging combines formal geometric and floral designs with inscriptions in Arabic, as well as figurative images. The central motif features opposing lions with human faces chained to the base of a stylised tree. The inscription at the top of the panel is a welcome used to greet those who have made a pilgrimage.":
    "在埃及各地的城镇，人们用这类色彩缤纷的大型纺织品搭建帐篷，在婚礼、葬礼和其他重要仪式上招待宾客。这件挂饰将规整的几何与花卉图案、阿拉伯文铭文以及具象图像融为一体。中央图案是一对相向而立、长着人脸的狮子，被锁链拴在一棵程式化的树的底部。饰板顶部的铭文是用来欢迎朝圣归来者的致辞。",
"The wearing of masks is an ancient human practice, found across the globe and dating back to at least 10,000 years ago. In African societies masks have been used for a variety of functions, including protection, performance, ritual, disguise and commemoration. This mask, collected by the Hungarian anthropologist Emil Torday in the early 1900s, is from the Democratic Republic of Congo and is associated with the Songye people. Masks of this form are used by the Bwami society that formerly exercised judicial power and performed at chiefly installations and during initiation ceremonies. It draws on the features of various wild animals in its composition.":
    "佩戴面具是人类一项古老的习俗，遍及全球，至少可追溯到一万年前。在非洲社会中，面具具有多种功能，包括保护、表演、仪式、伪装和纪念。这件面具由匈牙利人类学家埃米尔·托代于20世纪初收集，来自刚果民主共和国，与松耶人有关。这种形制的面具为布瓦米社团所用——该社团过去掌握司法权，并在酋长就职典礼和成年礼上进行表演。面具的造型融合了多种野生动物的特征。",
"Tree of life. Made by artists from Mozambique, 2004": "生命之树，莫桑比克艺术家创作，2004年",
"At over 3.5m (11.5ft) in height, this large sculptural tree was made from decommissioned firearms from Mozambique's 17-year civil war. The Tree of Life was created specifically for the British Museum by artists in Mozambique in 2004. The artwork is made from weapons collected by the Transforming Arms Into Tools project, which employed former child soldiers in Mozambique to dismantle guns. The weapon parts were swapped locally for farming tools, sewing machines, bicycles and building materials. This is one of a number of artworks in the gallery reflecting the vibrant and dynamic contemporary arts scene in Africa.":
    "这棵大型雕塑之树高逾3.5米（11.5英尺），由莫桑比克17年内战中退役的枪支制成。《生命之树》由莫桑比克艺术家于2004年专为大英博物馆创作，所用武器由“化武器为工具”项目收集——该项目雇用莫桑比克的前童兵拆解枪支，拆下的武器部件在当地被换成农具、缝纫机、自行车和建筑材料。本展厅中有多件艺术作品反映了非洲充满活力、蓬勃发展的当代艺术面貌，这便是其中之一。",
"Appliqué tent-cloth, Cairo, 1928 (before).": "贴花帐篷布，开罗，1928年（或更早）。",
}

# Strings intentionally left in English (iframe titles etc.)
SKIP = {"Blank", "8.email"}

# Context-specific raw replacements applied before the general pass
RAW = [
    ("<li>Visit&nbsp;<a", "<li>请参阅&nbsp;<a"),
]
